services:
  postgres:
    image: 'postgres:alpine'
    container_name: 'chat'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # volumes:
    #   dbtuto:/data/postgres-tuto
    ports:
      - "5432:5432"
    restart: unless-stopped
# volumes:
#     dbtuto:
#       external: true